### ISSUE TITLE
无法查看构建后的生成的报告

### ISSUE THREAD

**Issue by you-hengh** [antfu-collective/vite-plugin-inspect#108]
### Describe the bug

无法查看构建后生成的报告, 无论是使用`npx serve .vite-inspect` 或者是使用`live-server`插件

插件配置如下:
![2024-03-19_18-57-46](https://github.com/antfu/vite-plugin-inspect/assets/34816426/41746998-7ddd-4410-957e-1e2daccc612c)

使用`npx serve .vite-inspect`时,效果如下:
![2024-03-19_18-57-01](https://github.com/antfu/vite-plugin-inspect/assets/34816426/3d7ab16e-bf00-4389-b6bd-cc09fe06f68f)

单独使用vscode打开`.vite-inspect` 文件夹, 使用live-server插件启动`index.html`页面,显示如下:
![2024-03-19_19-00-07](https://github.com/antfu/vite-plugin-inspect/assets/34816426/7edc392c-df84-49d0-b7d9-4f7786b1e486)

我上传了生成的报告压缩包 地址是: https://wwk.lanzn.com/iLvBw1rwqnje

请问我如何正确打开生成的报告页面?

### Reproduction

https://wwk.lanzn.com/iLvBw1rwqnje

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) CoreT i7-13800H
    Memory: 17.50 GB / 31.74 GB
  Binaries:
    Node: 20.11.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 10.2.4 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1

其实我用的是chrome 版本 122.0.6261.129（正式版本） （64 位）

不知道为什么这个 envinfo 检测不出
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArthurDarkstone** [comment]
构建产物没有问题，打包输出的路径为 `docs/.vite-inspect` 。

请使用 `npx serve .\docs\.vite-inspect` 运行
