### ISSUE TITLE
Import failing during build

### ISSUE THREAD

**Issue by jpaquim** [antfu-collective/vite-plugin-inspect#125]
### Describe the bug

I'm getting this error, on a clean `pnpm create vite --template vanilla vite-app`, after downgrading `esbuild` to `0.24.0` (due to this current issue https://github.com/vitejs/vite/issues/19018):
```
x Build failed in 29ms
error during build:
[vite-plugin-inspect] ENOENT: no such file or directory, lstat '/Users/$USER/dev/vite-app/node_modules/.pnpm/vite-plugin-inspect@0.10.4_rollup@4.28.1_vite@6.0.4/node_modules/vite-plugin-inspect/dist/dist/client'
Error: ENOENT: no such file or directory, lstat '/Users/$USER/dev/vite-app/node_modules/.pnpm/vite-plugin-inspect@0.10.4_rollup@4.28.1_vite@6.0.4/node_modules/vite-plugin-inspect/dist/dist/client'
 ELIFECYCLE  Command failed with exit code 1.
```

My vite config:
```
import { defineConfig } from 'vite';
import inspect from 'vite-plugin-inspect';

export default defineConfig({
  plugins: [inspect({ build: true, outputDir: '.vite-inspect' })],
});
```

### Reproduction

https://github.com/jpaquim/vite-plugin-inspect-reproduction

### System Info

```Shell
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M2
    Memory: 1.07 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.local/share/pnpm/node
    npm: 10.8.2 - ~/.local/share/pnpm/npm
    pnpm: 9.15.1 - /opt/homebrew/bin/pnpm
    bun: 1.1.34 - ~/.local/share/mise/installs/bun/1.1.30/bin/bun
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.2
    Safari Technology Preview: 18.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by halcwb** [comment]
The esbuild problem is causing issues everywhere. I think that has to be resolved first. I can run the build by downgrading to esbuild 0.24.0, but then when I try the playground, I don't get the expected result of being able to inspect, I just see the original playground site.

**Comment by nekomeowww** [comment]
Nope, this is not introduced or caused by `esbuild`.

When take a closer look into:

```
x Build failed in 29ms
error during build:
[vite-plugin-inspect] ENOENT: no such file or directory, lstat 'path/of/node_modules/vite-plugin-inspect/dist/dist/client'
Error: ENOENT: no such file or directory, lstat 'path/of/node_modules/vite-plugin-inspect/dist/dist/client'
 ELIFECYCLE  Command failed with exit code 1.
```

You will discover that the path it looked into is `dist/dist`, which is caused by:

https://github.com/antfu-collective/vite-plugin-inspect/blob/2b34a5b3e02e0a0222821ae1a8573766b51d89d7/src/dir.ts#L8 

since `import.meta.url` will always be `dist` for published packages, concatting `import.meta.url` with `/dist/client` will result in duplicated `dist/dist` as shown above.

**Comment by userquin** [comment]
For some reason the dist folder has been refactored, maybe some rollup change, now the logic (src/dirs.ts) inside the shared folder, previous versions inside root folder.
