### ISSUE TITLE
[bug] Because of this #48d4 commit, update some dependencies;

### ISSUE THREAD

**Issue by LukerSpringtree** [antfu-collective/vite-plugin-inspect#126]
### Describe the bug

Can't  get the right Page

### Reproduction

https://github.com/antfu-collective/vite-plugin-inspect

### System Info

```Shell
`pn build`

then go to playground

`pn dev`
We can't get the right Page
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by userquin** [comment]
I guess the problem is solved with #128
