### ISSUE TITLE
Cannot see the intermediate state

### ISSUE THREAD

**Issue by halcwb** [antfu-collective/vite-plugin-inspect#129]
### Describe the bug

Added `Inspect()` to the vite plugin list. Expecting to see the intermediate state in the `--inspect` path, but shows the site content instead?

To reproduce:

`
git clone https://github.com/halcwb/test_vite
cd test_vite
npm install
npm run dev
`

You will get:

> test_vite_fable@0.0.0 dev
> vite

transpilling fsproj ./test_vite/Client/Client.fsproj
11:47:47 AM [vite] [fable]: configResolved: Configuration: Debug
11:47:47 AM [vite] [fable]: configResolved: Entry fsproj .test_vite/Client/Client.fsproj
11:47:47 AM [vite] [fable]: buildStart: Starting daemon
11:47:47 AM [vite] [fable]: buildStart: Initial project file change!
11:47:47 AM [vite] [fable]: projectChanged: dependent file ../test_vite/Client/Client.fsproj changed.
11:47:47 AM [vite] [fable]: compileProject: Full compile started of ./test_vite/Client/Client.fsproj
11:47:47 AM [vite] [fable]: compileProject: fable-library located at /Users/halcwb/Development/lab/test_vite/node_modules/@fable-org/fable-library-js
11:47:47 AM [vite] [fable]: compileProject: about to type-checked /Users/halcwb/Development/lab/test_vite/Client/Client.fsproj.
11:47:49 AM [vite] [fable]: compileProject: ./test_vite/Client/Client.fsproj was type-checked.
11:47:49 AM [vite] [fable]: compileProject: Full compile completed of ../test_vite/Client/Client.fsproj
Port 5173 is in use, trying another one...

  VITE v6.0.5  ready in 2241 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  Inspect: http://localhost:5174/__inspect/
  ➜  press h + enter to show help
11:47:53 AM [vite] [fable]: transform: ../test_vite/Client/Library.fs

### Reproduction

https://github.com/halcwb/test_vite

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 142.33 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.15.1 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
    bun: 1.1.40 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 17.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by userquin** [comment]
latest version is broken, check #128 , in the meantime you can pin 0.10.3 version
